# Created automatically by Cursor AI (2025-08-28)
[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "finance-workers-tests"
version = "0.0.1"
dependencies = [
  "pytest>=7.4",
]
